#!/bin/bash
source /usr/bin/zoptparse.sh
source /usr/bin/zcommon.sh
set -e
PATH=$script_dir:$PATH

zrequired=("remote-path")
zoptional=()

zoptparse $@ || exit 1

case $remote_path in
    warehouse:*)
        nfleval dls --short "${remote_path#*:}" 2>/dev/null | sed "s/^/warehouse:/"
        ;;
    localhost:*)
        # note: eval is necessary because argument to ls can contain *
        nfleval ls ${remote_path#*:} 2>/dev/null | sed "s/^/localhost:/;s,//,/,g"
        ;;
    *:*) # other hosts
        host=${remote_path%:*}
        path=${remote_path#*:}
        nfleval ssh $host "ls $path" 2>/dev/null | sed "s,^,$remote_path/,;s,//,/,g"
        ;;
    *)
        zerror "failure: unsupported remote path $remote_path"
        ;;
esac

exit 0

: <<=cut
=pod

=cut

