#!/bin/bash

script_dir=$(dirname $(readlink -f $0))
source /usr/bin/zoptparse.sh
source /usr/bin/zcommon.sh

zrequired=("cmdfile||text file, each line is a separate command to run in parallel") 

zoptional=( \
    "hosts|localhost|cluster-run hosts argument, typically a file containing a list of hosts." \
    "max-jobs-per-node|3|" \
    "use-parallel||Supply non trivial value for this to use gnu parallel as opposed to Zomojo's cluster-run." \
    "retries|2|cluster-run retries." \
    "timeout|9000|cluster-run timeout."\
    "job-name|zparallel-job|cluster-run job name."\
    "user-name|zoro|User name for cluster tool, if required." \
    "memory-required|4GB|Memory required for cluster tasks, if required." \
    "hilite-colour|magenta|Hilite colour."\
    )

zoptparse "$@" || exit 1

#work in progress
hilite_string="tee"
if rpm -q hilite 2>&1 > /dev/null; then
    hilite_string="hilite \"$hilite_colour=.[0-9]*/[0-9]*/*[0-9]*%\""
fi

if [ -n "$use_parallel" ]; then
    nfleval parallel \
    -j "$max_jobs_per_node" \
    --progress \
    --gnu \
    --arg-file="$cmdfile" \
    --no-notice 
else
    nfleval cluster-run \
    -n "$hosts" \
    -f "$cmdfile" \
    -c "$max_jobs_per_node" \
    -r "$retries" \
    -t "$timeout" \
    -j "$job_name"
# 
#else
#    nfleval kcg-cluster-run \
#    --list-of-cmds="$cmdfile" \
#    --job-name="$job_name" \
#    --user-name="$user_name" \
#    --memory-required="$memory_required" \
#    --timeout="$timemout" \
#    --retries="$retries" 
fi  

: <<=cut
=pod

=cut

